{{- $config := required "codeai_cluster_config is required" (index .Values "codeai_cluster_config") -}}
{{- $iamRoleArn := .Values.sharedResources.iamRoleArn | default (printf "%s:role/%s-eso-kargo-external-secret-stores" (required "codeai_cluster_config.iam_arn_prefix is required" (index $config "iam_arn_prefix")) (required "codeai_cluster_config.cluster_name is required" (index $config "cluster_name"))) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa-kargo-shared-resources
  namespace: {{ .Values.sharedResources.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $iamRoleArn | quote }}
