apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.dexSecretStore.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.dexSecretStore.iamRoleArn | quote }}
