image: ghcr.io/code-dot-org/code-dot-org:git-9b936310f503f271e4322f01d656dcfbb7d7fffb # updated by k8s-commit-to-kargo-warehouse.yml
dnsName: studio.levelbuilder
autoscaling:
  maxReplicas: 1
locals.yml:
  stack_name: levelbuilder
  override_dashboard: studio.levelbuilder.k8s.code.org
