image: ghcr.io/code-dot-org/code-dot-org:git-802a5176ebd685fd7629e0e60b4975396c98642f # updated by k8s-commit-to-kargo-warehouse.yml
dnsName: studio.levelbuilder
autoscaling:
  maxReplicas: 1
locals.yml:
  stack_name: levelbuilder
  override_dashboard: studio.levelbuilder.k8s.code.org
