image: ghcr.io/code-dot-org/code-dot-org:git-c82a958eb7f31112d7b5a5fa943c29a1749f03a0 # updated by k8s-commit-to-kargo-warehouse.yml
dnsName: studio.levelbuilder
autoscaling:
  maxReplicas: 1
locals.yml:
  stack_name: levelbuilder
  override_dashboard: studio.levelbuilder.k8s.code.org
