{{- $clusterName := .Values.codeai_cluster_config.cluster_name -}}
{{- $oidcProviderArn := .Values.codeai_cluster_config.oidc_provider_arn -}}
{{- $oidcHost := trimPrefix "https://" .Values.codeai_cluster_config.cluster_oidc_issuer_url -}}
{{- $namespace := include "aws-resources.namespace" . -}}
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  name: aws-load-balancer-controller
  namespace: {{ $namespace }}
  annotations:
    crossplane.io/external-name: {{ printf "%s-aws-load-balancer-controller" $clusterName | quote }}
spec:
{{ include "aws-resources.providerConfigRef" . | indent 2 }}
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Principal": {
              "Federated": {{ $oidcProviderArn | quote }}
            },
            "Condition": {
              "StringEquals": {
                "{{ $oidcHost }}:sub": "system:serviceaccount:kube-system:aws-load-balancer-controller-sa",
                "{{ $oidcHost }}:aud": "sts.amazonaws.com"
              }
            }
          }
        ]
      }
    description: IRSA for aws-load-balancer-controller project
    forceDetachPolicies: true
    path: /
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Policy
metadata:
  name: aws-load-balancer-controller
  namespace: {{ $namespace }}
  annotations:
    crossplane.io/external-name: {{ printf "%s-aws-load-balancer-controller" $clusterName | quote }}
spec:
{{ include "aws-resources.providerConfigRef" . | indent 2 }}
  forProvider:
    description: IAM Policy for AWS Load Balancer Controller
    path: /
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "*",
            "Condition": {
              "StringEquals": {
                "iam:AWSServiceName": "elasticloadbalancing.amazonaws.com"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:DescribeTargetHealth",
              "elasticloadbalancing:DescribeTargetGroups",
              "elasticloadbalancing:DescribeTargetGroupAttributes",
              "elasticloadbalancing:DescribeTags",
              "elasticloadbalancing:DescribeSSLPolicies",
              "elasticloadbalancing:DescribeRules",
              "elasticloadbalancing:DescribeLoadBalancers",
              "elasticloadbalancing:DescribeLoadBalancerAttributes",
              "elasticloadbalancing:DescribeListeners",
              "elasticloadbalancing:DescribeListenerCertificates",
              "ec2:GetCoipPoolUsage",
              "ec2:DescribeVpcs",
              "ec2:DescribeVpcPeeringConnections",
              "ec2:DescribeTags",
              "ec2:DescribeSubnets",
              "ec2:DescribeSecurityGroups",
              "ec2:DescribeNetworkInterfaces",
              "ec2:DescribeInternetGateways",
              "ec2:DescribeInstances",
              "ec2:DescribeCoipPools",
              "ec2:DescribeAvailabilityZones",
              "ec2:DescribeAddresses",
              "ec2:DescribeAccountAttributes"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "wafv2:GetWebACLForResource",
              "wafv2:GetWebACL",
              "wafv2:DisassociateWebACL",
              "wafv2:AssociateWebACL",
              "waf-regional:GetWebACLForResource",
              "waf-regional:GetWebACL",
              "waf-regional:DisassociateWebACL",
              "waf-regional:AssociateWebACL",
              "shield:GetSubscriptionState",
              "shield:DescribeProtection",
              "shield:DeleteProtection",
              "shield:CreateProtection",
              "iam:ListServerCertificates",
              "iam:GetServerCertificate",
              "cognito-idp:DescribeUserPoolClient",
              "acm:ListCertificates",
              "acm:DescribeCertificate"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "ec2:RevokeSecurityGroupIngress",
              "ec2:AuthorizeSecurityGroupIngress"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": "ec2:CreateSecurityGroup",
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": "ec2:CreateTags",
            "Resource": "arn:aws:ec2:*:*:security-group/*",
            "Condition": {
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "false"
              },
              "StringEquals": {
                "ec2:CreateAction": "CreateSecurityGroup"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "ec2:DeleteTags",
              "ec2:CreateTags"
            ],
            "Resource": "arn:aws:ec2:*:*:security-group/*",
            "Condition": {
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "true",
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "ec2:RevokeSecurityGroupIngress",
              "ec2:DeleteSecurityGroup",
              "ec2:AuthorizeSecurityGroupIngress"
            ],
            "Resource": "*",
            "Condition": {
              "Null": {
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:CreateTargetGroup",
              "elasticloadbalancing:CreateLoadBalancer"
            ],
            "Resource": "*",
            "Condition": {
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:DeleteRule",
              "elasticloadbalancing:DeleteListener",
              "elasticloadbalancing:CreateRule",
              "elasticloadbalancing:CreateListener"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:RemoveTags",
              "elasticloadbalancing:AddTags"
            ],
            "Resource": [
              "arn:aws:elasticloadbalancing:*:*:targetgroup/*/*",
              "arn:aws:elasticloadbalancing:*:*:loadbalancer/net/*/*",
              "arn:aws:elasticloadbalancing:*:*:loadbalancer/app/*/*"
            ],
            "Condition": {
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "true",
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:RemoveTags",
              "elasticloadbalancing:AddTags"
            ],
            "Resource": [
              "arn:aws:elasticloadbalancing:*:*:listener/net/*/*/*",
              "arn:aws:elasticloadbalancing:*:*:listener/app/*/*/*",
              "arn:aws:elasticloadbalancing:*:*:listener-rule/net/*/*/*",
              "arn:aws:elasticloadbalancing:*:*:listener-rule/app/*/*/*"
            ]
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:SetSubnets",
              "elasticloadbalancing:SetSecurityGroups",
              "elasticloadbalancing:SetIpAddressType",
              "elasticloadbalancing:ModifyTargetGroupAttributes",
              "elasticloadbalancing:ModifyTargetGroup",
              "elasticloadbalancing:ModifyLoadBalancerAttributes",
              "elasticloadbalancing:DeleteTargetGroup",
              "elasticloadbalancing:DeleteLoadBalancer"
            ],
            "Resource": "*",
            "Condition": {
              "Null": {
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": "elasticloadbalancing:AddTags",
            "Resource": [
              "arn:aws:elasticloadbalancing:*:*:targetgroup/*/*",
              "arn:aws:elasticloadbalancing:*:*:loadbalancer/net/*/*",
              "arn:aws:elasticloadbalancing:*:*:loadbalancer/app/*/*"
            ],
            "Condition": {
              "Null": {
                "aws:RequestTag/elbv2.k8s.aws/cluster": "false"
              },
              "StringEquals": {
                "elasticloadbalancing:CreateAction": [
                  "CreateTargetGroup",
                  "CreateLoadBalancer"
                ]
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:RegisterTargets",
              "elasticloadbalancing:DeregisterTargets"
            ],
            "Resource": "arn:aws:elasticloadbalancing:*:*:targetgroup/*/*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:SetWebAcl",
              "elasticloadbalancing:RemoveListenerCertificates",
              "elasticloadbalancing:ModifyRule",
              "elasticloadbalancing:ModifyListener",
              "elasticloadbalancing:AddListenerCertificates"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:DescribeTrustStores",
              "elasticloadbalancing:DescribeListenerAttributes",
              "elasticloadbalancing:DescribeCapacityReservation",
              "ec2:GetSecurityGroupsForVpc",
              "ec2:DescribeRouteTables",
              "ec2:DescribeIpamPools"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "elasticloadbalancing:ModifyListenerAttributes",
              "elasticloadbalancing:ModifyIpPools",
              "elasticloadbalancing:ModifyCapacityReservation"
            ],
            "Resource": "*",
            "Condition": {
              "Null": {
                "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": "elasticloadbalancing:SetRulePriorities",
            "Resource": "*"
          }
        ]
      }
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: aws-load-balancer-controller
  namespace: {{ $namespace }}
spec:
{{ include "aws-resources.providerConfigRef" . | indent 2 }}
  forProvider:
    policyArnRef:
      name: aws-load-balancer-controller
    roleRef:
      name: aws-load-balancer-controller
