apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusterdnscertificates.infra.code.org
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  group: infra.code.org
  names:
    kind: XClusterDNSCertificate
    plural: xclusterdnscertificates
  scope: Namespaced
  defaultCompositionRef:
    name: codeai-k8s-cluster-dns-certificate
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - clusterName
                - clusterRegion
                - clusterOidcIssuerUrl
                - clusterSubdomain
                - oidcProviderArn
                - parentDomainZoneId
                - singleNamespaceEnvironmentTypes
              properties:
                clusterName:
                  type: string
                clusterRegion:
                  type: string
                clusterOidcIssuerUrl:
                  type: string
                clusterSubdomain:
                  type: string
                oidcProviderArn:
                  type: string
                parentDomainZoneId:
                  type: string
                singleNamespaceEnvironmentTypes:
                  type: array
                  items:
                    type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: codeai-k8s-cluster-dns-certificate
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  compositeTypeRef:
    apiVersion: infra.code.org/v1alpha1
    kind: XClusterDNSCertificate
  mode: Pipeline
  pipeline:
    - step: render-managed-resources
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          options:
            - missingkey=error
          template: |
{{ .Files.Get "composition-templates/cluster-subdomain.yaml" | indent 12 }}
    - step: auto-ready
      functionRef:
        name: function-auto-ready
