{{- if eq .Values.provider "aws" }}
{{- $clusterName := .Values.codeai_cluster_config.cluster_name -}}
{{- $clusterRegion := .Values.codeai_cluster_config.cluster_region -}}
{{- $oidcProviderArn := .Values.codeai_cluster_config.oidc_provider_arn -}}
{{- $oidcHost := trimPrefix "https://" .Values.codeai_cluster_config.cluster_oidc_issuer_url -}}
{{- $accountID := index (splitList ":" $oidcProviderArn) 4 -}}
{{- range $env := .Values.codeai_cluster_config.single_namespace_environment_types }}
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  name: standard-envtypes-eso-{{ $env }}
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
    crossplane.io/external-name: {{ printf "%s-eso-%s" $clusterName $env | quote }}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    tags:
      code.ai/cluster: {{ $clusterName | quote }}
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Principal": {
              "Federated": {{ $oidcProviderArn | quote }}
            },
            "Condition": {
              "StringEquals": {
                "{{ $oidcHost }}:sub": "system:serviceaccount:{{ $env }}:external-secrets-sa-{{ $env }}",
                "{{ $oidcHost }}:aud": "sts.amazonaws.com"
              }
            }
          }
        ]
      }
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicy
metadata:
  name: standard-envtypes-eso-{{ $env }}
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
    crossplane.io/external-name: secrets-manager-access
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    roleRef:
      name: standard-envtypes-eso-{{ $env }}
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "secretsmanager:ListSecrets",
              "secretsmanager:BatchGetSecretValue"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": [
              "arn:aws:secretsmanager:{{ $clusterRegion }}:{{ $accountID }}:secret:{{ $env }}/cdo/*",
              "arn:aws:secretsmanager:{{ $clusterRegion }}:{{ $accountID }}:secret:CfnStack/{{ $env }}/*"
            ]
          }
        ]
      }
{{- end }}
{{- end }}
