apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app.kubernetes.io/name: helloworld
spec:
  selector:
    app.kubernetes.io/name: helloworld
  ports:
    - name: http
      port: 80
      targetPort: http
