{{- $config := required "codeai_cluster_config is required" (index .Values "codeai_cluster_config") -}}
{{- $controller := required "aws-load-balancer-controller values are required" (index .Values "aws-load-balancer-controller") -}}
{{- $controllerChart := index .Subcharts "aws-load-balancer-controller" -}}
{{- $serviceAccount := index $controller "serviceAccount" -}}
{{- $annotations := merge (dict) (default (dict) (index $serviceAccount "annotations")) (dict "eks.amazonaws.com/role-arn" (printf "%s:role/%s-aws-load-balancer-controller" (required "codeai_cluster_config.iam_arn_prefix is required" (index $config "iam_arn_prefix")) (required "codeai_cluster_config.cluster_name is required" (index $config "cluster_name")))) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-load-balancer-controller.serviceAccountName" (dict "Values" $controller "Chart" $controllerChart.Chart "Release" .Release) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-load-balancer-controller.labels" (dict "Values" $controller "Chart" $controllerChart.Chart "Release" .Release) | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ index $serviceAccount "automountServiceAccountToken" }}
{{- with (index $serviceAccount "imagePullSecrets") }}
imagePullSecrets:
{{ toYaml . }}
{{- end }}
