#============================================================
# Create a shared GatewayClass for AWS Load Balancer Controller-backed Gateways.
# Individual services should reference this class instead of creating their own.
#============================================================

apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: {{ .Values.gateway.loadBalancerConfig.name }}
  namespace: {{ .Values.gateway.loadBalancerConfig.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  scheme: {{ .Values.gateway.loadBalancerConfig.scheme | quote }}
  listenerConfigurations:
    - alpnPolicy: None
      protocolPort: "HTTPS:443"
{{- with .Values.gateway.loadBalancerConfig.defaultCertificateArn }}
      defaultCertificate: {{ . | quote }}
{{- end }}
