{{- if eq .Values.provider "aws" }}
{{- $clusterName := .Values.codeai_cluster_config.cluster_name -}}
{{- $clusterRegion := .Values.codeai_cluster_config.cluster_region -}}
{{- $oidcProviderArn := .Values.codeai_cluster_config.oidc_provider_arn -}}
{{- $oidcHost := trimPrefix "https://" .Values.codeai_cluster_config.cluster_oidc_issuer_url -}}
{{- $accountID := index (splitList ":" $oidcProviderArn) 4 -}}
{{- $namespace := include "dex.aws.namespace" . -}}
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  name: dex-external-secrets
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
    crossplane.io/external-name: {{ printf "%s-eso-dex" $clusterName | quote }}
spec:
{{ include "dex.aws.providerConfigRef" . | indent 2 }}
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Principal": {
              "Federated": {{ $oidcProviderArn | quote }}
            },
            "Condition": {
              "StringEquals": {
                "{{ $oidcHost }}:sub": "system:serviceaccount:dex:external-secrets-sa-dex",
                "{{ $oidcHost }}:aud": "sts.amazonaws.com"
              }
            }
          }
        ]
      }
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicy
metadata:
  name: dex-external-secrets
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
    crossplane.io/external-name: secrets-manager-access
spec:
{{ include "dex.aws.providerConfigRef" . | indent 2 }}
  forProvider:
    roleRef:
      name: dex-external-secrets
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": [
              "arn:aws:secretsmanager:{{ $clusterRegion }}:{{ $accountID }}:secret:k8s/tofu/{{ $clusterName }}/dex_google_service_account_key*",
              "arn:aws:secretsmanager:{{ $clusterRegion }}:{{ $accountID }}:secret:k8s/tofu/{{ $clusterName }}/dex_google_client_secret*"
            ]
          }
        ]
      }
{{- end }}
