apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/code-dot-org/k8s-gitops.git
      targetRevision: main
      path: apps/monitoring/chart
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/apps/infra/codeai-cluster-config.values.yaml
          - $values/apps/monitoring/values.yaml
    - repoURL: https://github.com/code-dot-org/k8s-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
