apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimic-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/code-dot-org/k8s-gitops.git
    targetRevision: main
    path: mimic/apps/app-of-apps
    directory:
      include: applicationset.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
