# Defaults. Overridden at deploy time by $values/apps/helloworld/values.yaml,
# whose `image` key is rewritten by Kargo on each promotion.
image: docker.io/library/nginx:1.30.2-alpine-slim
dnsName: hello
replicas: 1
