apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  sources:
    - repoURL: https://github.com/code-dot-org/k8s-gitops.git
      targetRevision: main
      path: apps/infra/dex/chart
      helm:
        releaseName: dex
        valueFiles:
          - $values/apps/infra/codeai-cluster-config.values.yaml
    - repoURL: https://github.com/code-dot-org/k8s-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
