image: ghcr.io/code-dot-org/code-dot-org:git-bc2a4f7b2c855b2419799e443a2861a91468c615 # updated by k8s-commit-to-kargo-warehouse.yml
dnsName: studio.production
autoscaling:
  minReplicas: 1
  maxReplicas: 2
resources:
  requests:
    ephemeralStorage: 30Gi
locals.yml:
  stack_name: autoscale-prod
  override_dashboard: studio.production.k8s.code.org
