image: ghcr.io/code-dot-org/code-dot-org:git-ebcd68770bcbcc0493539aa15652ae18b08a1164 # updated by k8s-commit-to-kargo-warehouse.yml
autoscaling:
  minReplicas: 1
  maxReplicas: 2
resources:
  requests:
    ephemeralStorage: 30Gi
locals.yml:
  stack_name: autoscale-prod
