image: ghcr.io/code-dot-org/code-dot-org:git-d39798c5dead3534ee6c1a51e31a127fa8ac8beb # updated by k8s-commit-to-kargo-warehouse.yml
dnsName: studio.production
autoscaling:
  minReplicas: 1
  maxReplicas: 2
resources:
  requests:
    ephemeralStorage: 30Gi
locals.yml:
  stack_name: autoscale-prod
  override_dashboard: studio.production.k8s.code.org
