# We create these namespaces in kargo-external-secret-stores.tf in code-dot-org
# because Tofu manages SecretStores and ExternalSecrets inside them and it 
# got here first ;-)
global:
  systemResources:
    createNamespace: false
  sharedResources:
    createNamespace: false

webhooks:
  # The Kargo chart otherwise expects cert-manager to mint webhook certs.
  register: false

api:
  host: kargo.k8s.code.org
  adminAccount:
    enabled: false
  secretManagementEnabled: false
  oidc:
    enabled: true
    issuerURL: https://dex.k8s.code.org
    clientID: kargo.k8s.code.org
    cliClientID: kargo.k8s.code.org-cli
    admins:
      claims:
        groups:
          - engineers@code.org
          - infrastructure@code.org
    viewers:
      claims:
        groups:
          - all@code.org
          - trusted-contributors@code.org
          - product@code.org
  tls:
    enabled: false
    terminatedUpstream: true
  ingress:
    enabled: true
    pathType: Prefix
    tls:
      enabled: false
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/backend-protocol: HTTP
externalWebhooksServer:
  enabled: true
  host: kargo.k8s.code.org
  tls:
    enabled: false
    terminatedUpstream: true

webhooksServer:
  enabled: false

extraObjects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: kargo-controller-crd-discovery
    rules:
      - apiGroups:
          - apiextensions.k8s.io
        resources:
          - customresourcedefinitions
        verbs:
          - get
          - list
          - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: kargo-controller-crd-discovery
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: kargo-controller-crd-discovery
    subjects:
      - kind: ServiceAccount
        name: kargo-controller
        namespace: kargo
