RAILS_ENV: production
dnsName: studio.production
locals.yml:
  override_dashboard: studio.production.k8s.code.org
# dashboard_workers: 32
healthChecks:
  enabled: true
require_external_secrets: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
