RAILS_ENV: production
# dashboard_workers: 32
healthChecks:
  enabled: true
require_external_secrets: true
renderedBranches:
  deterministicLocalSecrets: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
