RAILS_ENV: test
# dashboard_workers: 65
healthChecks:
  enabled: true
require_external_secrets: true
extraEnv:
  - name: PERMIT_UNKNOWN_PROPERTIES_IN_CDO
    value: "1"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
