apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-project-codeai
  namespace: kargo-project-codeai
spec:
  promotionPolicies:
    - stage: staging
      autoPromotionEnabled: true
    - stage: test
      autoPromotionEnabled: false
    - stage: production
      autoPromotionEnabled: false
    - stage: levelbuilder
      autoPromotionEnabled: false
