apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-project-codeai
  namespace: kargo-project-codeai
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/code-dot-org/cdo-rails
        imageSelectionStrategy: Digest
        # Under the Digest strategy this field names the mutable tag to watch.
        constraint: latest
