apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: codeai
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/code-dot-org/k8s-gitops.git
        revision: main
        files:
          - path: apps/codeai/releases/*/config.yaml
  template:
    metadata:
      name: codeai-{{path.basename}}
      labels:
        app.kubernetes.io/managed-by: kargo
        kargo.akuity.io/project: cdo
    spec:
      project: default
      sources:
        - repoURL: https://github.com/code-dot-org/code-dot-org.git
          targetRevision: '{{sourceRevision}}'
          path: k8s/helm
          helm:
            releaseName: '{{path.basename}}'
            valueFiles:
              - $values/apps/codeai/env-types/{{envType}}.values.yaml
              - $values/apps/codeai/releases/{{path.basename}}/values.yaml
        - repoURL: https://github.com/code-dot-org/k8s-gitops.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
