codeai_cluster_config:
  cluster_name:
  cluster_region:
  iam_arn_prefix:

sharedResources:
  namespace: kargo-shared-resources
  iamRoleArn: ""

systemResources:
  namespace: kargo-system-resources
  secretStore:
    name: aws-secrets-manager-store-kargo-system-resources
    serviceAccountName: external-secrets-sa-kargo-system-resources
    iamRoleArn:

  externalSecret:
    name: github-org-webhook-secret
    secretStoreName: aws-secrets-manager-store-kargo-system-resources
    awsSecretName: k8s/tofu/codeai-k8s/kargo/github_org_webhook_secret
