apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# TODO: set the path to the base correctly (if any?) for the kargo-architecture plan
# resources:
#   - ../../deployments/staging/deploy/base
components:
  - ../components/staging
