apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stress-argo-trace-secondary-root
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/code-dot-org/k8s-gitops.git
        revision: main
        files:
          - path: argo-trace-stress-test/apps/secondary/*/application.yaml
  template:
    metadata:
      name: '{{.metadata.name}}'
    spec:
      project: '{{if hasKey .spec "project"}}{{.spec.project}}{{else}}default{{end}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
  templatePatch: |
    {{- if or (hasKey .spec "source") (hasKey .spec "sources") }}
    metadata: {{ .metadata | toJson }}
    spec: {{ omit .spec "project" | toJson }}
    {{- end }}
