{{- $config := required "codeai_cluster_config is required" (index .Values "codeai_cluster_config") -}}
{{- $externalDns := required "external-dns values are required" (index .Values "external-dns") -}}
{{- $externalDnsChart := index .Subcharts "external-dns" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "external-dns.serviceAccountName" (dict "Values" $externalDns "Chart" $externalDnsChart.Chart "Release" .Release) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns.labels" (dict "Values" $externalDns "Chart" $externalDnsChart.Chart "Release" .Release) | nindent 4 }}
  {{- with (index $externalDns "serviceAccount" "labels") }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    eks.amazonaws.com/role-arn: {{ printf "%s:role/%s-external-dns" (required "codeai_cluster_config.iam_arn_prefix is required" (index $config "iam_arn_prefix")) (required "codeai_cluster_config.cluster_name is required" (index $config "cluster_name")) | quote }}
automountServiceAccountToken: {{ index $externalDns "serviceAccount" "automountServiceAccountToken" }}
