apiVersion: v2
name: crossplane-codeai-k8s
description: Local chart for Crossplane on codeai-k8s
type: application
version: 0.1.16

dependencies:
  - name: crossplane
    repository: https://charts.crossplane.io/stable
    version: 2.2.0
