codeai_cluster_config:
  cluster_name:
  iam_arn_prefix:

crossplane:
  replicas: 1

  resourcesCrossplane:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1024Mi

  resourcesRBACManager:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 512Mi

  providers:
    aws:
      iamRoleArn:

provider:
  aws:
    acm:
      enabled: true
    cloudfront:
      enabled: false
    elasticache:
      enabled: false
    family:
      enabled: true
    iam:
      enabled: true
    rds:
      enabled: false
    route53:
      enabled: true
    secretsmanager:
      enabled: false
