{{- if eq .Values.provider "aws" }}
{{- $clusterName := .Values.codeai_cluster_config.cluster_name -}}
{{- $clusterRegion := .Values.codeai_cluster_config.cluster_region -}}
{{- $oidcProviderArn := .Values.codeai_cluster_config.oidc_provider_arn -}}
{{- $oidcHost := trimPrefix "https://" .Values.codeai_cluster_config.cluster_oidc_issuer_url -}}
{{- $accountID := index (splitList ":" $oidcProviderArn) 4 -}}
{{- $namespace := include "kargo-secrets.aws.namespace" . -}}
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  name: kargo-external-secret-stores
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
    crossplane.io/external-name: {{ printf "%s-eso-kargo-external-secret-stores" $clusterName | quote }}
spec:
{{ include "kargo-secrets.aws.providerConfigRef" . | indent 2 }}
  forProvider:
    tags:
      code.ai/cluster: {{ $clusterName | quote }}
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Principal": {
              "Federated": {{ $oidcProviderArn | quote }}
            },
            "Condition": {
              "StringEquals": {
                "{{ $oidcHost }}:sub": [
                  "system:serviceaccount:kargo-shared-resources:external-secrets-sa-kargo-shared-resources",
                  "system:serviceaccount:kargo-system-resources:external-secrets-sa-kargo-system-resources"
                ],
                "{{ $oidcHost }}:aud": "sts.amazonaws.com"
              }
            }
          }
        ]
      }
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicy
metadata:
  name: kargo-external-secret-stores
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
    crossplane.io/external-name: secrets-manager-access
spec:
{{ include "kargo-secrets.aws.providerConfigRef" . | indent 2 }}
  forProvider:
    roleRef:
      name: kargo-external-secret-stores
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": "arn:aws:secretsmanager:{{ $clusterRegion }}:{{ $accountID }}:secret:k8s/tofu/{{ $clusterName }}/kargo/*"
          }
        ]
      }
{{- end }}
