{{- if eq (include "crossplane.isAnyAWSProviderEnabled" .) "true" -}}

{{- $config := required "codeai_cluster_config is required" (index .Values "codeai_cluster_config") -}}
{{- $iamRoleArn := .Values.crossplane.providers.aws.iamRoleArn | default (printf "%s:role/%s-crossplane-aws" (required "codeai_cluster_config.iam_arn_prefix is required" (index $config "iam_arn_prefix")) (required "codeai_cluster_config.cluster_name is required" (index $config "cluster_name"))) -}}

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: "aws-runtime-config"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 500m
                  memory: 1Gi
  serviceAccountTemplate:
    metadata:
      # this service account name must match the one in crossplane-aws.tf
      name: "crossplane-aws"
      annotations:
        eks.amazonaws.com/role-arn: {{ $iamRoleArn | quote }}
{{- end }}
