apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: "provider-aws-route53"
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  package: "xpkg.upbound.io/upbound/provider-aws-route53:v2.5.1"
  runtimeConfigRef:
    name: "provider-aws"
