{{- if .Values.provider.aws.elasticache.enabled -}}
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-aws-elasticache
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-elasticache:v2.5.1
  runtimeConfigRef:
    name: crossplane-aws-runtime-config
{{- end }}
