apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: standard-envtypes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/target/deletionPolicy
        - /spec/target/template/engineVersion
        - /spec/target/template/mergePolicy
      jqPathExpressions:
        - .spec.data[]?.remoteRef.conversionStrategy
        - .spec.data[]?.remoteRef.decodingStrategy
        - .spec.data[]?.remoteRef.metadataPolicy
        - .spec.dataFrom[]?.find.conversionStrategy
        - .spec.dataFrom[]?.find.decodingStrategy
    - group: external-secrets.io
      kind: ClusterExternalSecret
      jsonPointers:
        - /spec/externalSecretSpec/target/deletionPolicy
        - /spec/externalSecretSpec/target/template/engineVersion
        - /spec/externalSecretSpec/target/template/mergePolicy
      jqPathExpressions:
        - .spec.externalSecretSpec.data[]?.remoteRef.conversionStrategy
        - .spec.externalSecretSpec.data[]?.remoteRef.decodingStrategy
        - .spec.externalSecretSpec.data[]?.remoteRef.metadataPolicy
        - .spec.externalSecretSpec.dataFrom[]?.find.conversionStrategy
        - .spec.externalSecretSpec.dataFrom[]?.find.decodingStrategy
  sources:
    - repoURL: https://github.com/code-dot-org/k8s-gitops.git
      targetRevision: main
      path: apps/infra/standard-envtypes/chart
      helm:
        releaseName: standard-envtypes
        valueFiles:
          - $values/apps/infra/codeai-cluster-config.values.yaml
    - repoURL: https://github.com/code-dot-org/k8s-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - CreateNamespace=true
