apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stress-argo-trace-crossplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/code-dot-org/k8s-gitops.git
    targetRevision: main
    path: argo-trace-stress-test/apps/primary/crossplane/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: stress-argo-trace-crossplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
