apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  # Intentionally no resources finalizer here to cascade delete k8s parts of Argo,
  # because ArgoCD can't safely delete itself live without shit going crazy and
  # wedging. We have it delete its Application but leave Argo pods etc running.
  #
  # Final teardown of the Argo install is owned by the bootstrap Helm release in
  # k8s-gitops/bootstrap/codeai-k8s/cluster-infra-argocd/argocd-bootstrap.tf
  #
  # This gives us symmetry in bootstrap and destroy! (PS: and it works)
spec:
  project: default
  sources:
    - repoURL: https://github.com/code-dot-org/k8s-gitops.git
      targetRevision: main
      path: apps/infra/argocd/chart
      helm:
        releaseName: argocd
        valueFiles:
          - $values/apps/infra/codeai-cluster-config.values.yaml
    - repoURL: https://github.com/code-dot-org/k8s-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
