apiVersion: v1
kind: Service
metadata:
  name: stress-argo-trace-broken-statefulset
spec:
  clusterIP: None
  selector:
    app: stress-argo-trace-broken-statefulset
  ports:
    - name: dummy
      port: 80
      targetPort: 80
