apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: kargo-project-codeai
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-project-codeai
      sources:
        stages:
          - review-infra-changes
  promotionTemplate:
    spec:
      vars:
        - name: gitopsRepo
          value: https://github.com/code-dot-org/k8s-gitops.git
        - name: targetBranch
          value: stage/production
      steps:
        - uses: git-clone
          as: gitops
          config:
            repoURL: ${{ vars.gitopsRepo }}
            checkout:
              - as: production
                branch: ${{ vars.targetBranch }}
                path: ./out
                sparse:
                  - apps/codeai/deployments/production/deploy
        - uses: argocd-update
          config:
            apps:
              - name: codeai-production
                sources:
                  - repoURL: ${{ vars.gitopsRepo }}
                    desiredRevision: ${{ outputs.gitops.commits.production }}
