apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: kargo-project-codeai
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: codeai-builds
      sources:
        stages:
          - review-infra-changes
  promotionTemplate:
    spec:
      vars:
        - name: gitopsRepo
          value: https://github.com/code-dot-org/k8s-gitops.git
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitopsRepo }}
            checkout:
              - commit: ${{ commitFrom(vars.gitopsRepo, warehouse('codeai-builds')).ID }}
                path: ./freight
              - branch: main
                path: ./gitops
        - uses: yaml-parse
          as: build-lock
          config:
            path: ./freight/warehouses/codeai/builds/current.yaml
            outputs:
              - name: releaseId
                fromExpression: releaseId
              - name: gitCommit
                fromExpression: gitCommit
              - name: imageRef
                fromExpression: image.ref
              - name: packagingKind
                fromExpression: packaging.kind
              - name: sourcePath
                fromExpression: packaging.sourcePath
        - uses: yaml-update
          config:
            path: ./gitops/apps/codeai/deployments/production/deployment.yaml
            updates:
              - key: targetRevision
                value: ${{ outputs['build-lock'].gitCommit }}
        - uses: yaml-update
          config:
            path: ./gitops/apps/codeai/deployments/production/values.yaml
            updates:
              - key: image
                value: ${{ outputs['build-lock'].imageRef }}
        - uses: git-commit
          config:
            path: ./gitops
            message: |
              Promote production to ${{ outputs['build-lock'].releaseId }} [skip ci]
        - uses: git-push
          config:
            path: ./gitops
