apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: kargo-project-codeai
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: codeai-builds
      sources:
        stages:
          - review-infra-changes
  vars:
    - name: gitopsRepo
      value: https://github.com/code-dot-org/k8s-gitops.git
    - name: legacyEnv
      value: production
    - name: targetBranch
      value: stage/production
    - name: renderPath
      value: apps/codeai/deployments/production/deploy
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitopsRepo }}
            checkout:
              - commit: ${{ commitFrom(vars.gitopsRepo, warehouse('codeai-builds')).ID }}
                path: ./freight
                sparse:
                  - warehouses/codeai/builds/current.yaml
              - branch: main
                path: ./gate
                sparse:
                  - warehouses/codeai/legacy-gitflow/production/merged
              - branch: ${{ vars.targetBranch }}
                path: ./out
                sparse:
                  - ${{ vars.renderPath }}
        - uses: yaml-parse
          as: build-lock
          config:
            path: ./freight/warehouses/codeai/builds/current.yaml
            outputs:
              - name: releaseId
                fromExpression: releaseId
        - uses: yaml-parse
          as: legacy-gate
          config:
            path: ./gate/warehouses/codeai/legacy-gitflow/${{ vars.legacyEnv }}/merged/${{ outputs['build-lock'].releaseId }}.yaml
            outputs:
              - name: mergedAt
                fromExpression: mergedAt
