apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: review-infra-changes
  namespace: kargo-project-codeai
spec:
  vars:
    - name: gitopsRepo
      value: https://github.com/code-dot-org/k8s-gitops.git
    - name: sourceRepo
      value: https://github.com/code-dot-org/code-dot-org.git
    - name: imageRepo
      value: ghcr.io/code-dot-org/code-dot-org
    - name: deployment
      value: production
    - name: envType
      value: production
    - name: targetBranch
      value: stage/production
    - name: renderPath
      value: apps/codeai/deployments/production/deploy
    - name: sourceCommit
      value: ${{ commitFrom(vars.sourceRepo).ID }}
  requestedFreight:
    - origin:
        kind: Warehouse
        name: codeai
      sources:
        stages:
          - test
        autoPromotionOptions:
          selectionPolicy: MatchUpstream
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitopsRepo }}
            checkout:
              - branch: main
                path: ./meta
              - branch: ${{ vars.targetBranch }}
                create: true
                path: ./out
        - uses: git-clone
          config:
            repoURL: ${{ vars.sourceRepo }}
            checkout:
              - commit: ${{ vars.sourceCommit }}
                path: ./src
                sparse:
                  - k8s/kustomize
        - uses: git-clear
          config:
            path: ./out
        - uses: copy
          config:
            inPath: ./meta/apps/codeai/kargo/templates/deploy
            outPath: ./render/deploy
        - uses: copy
          config:
            inPath: ./meta/apps/codeai/envTypes/${{ vars.envType }}
            outPath: ./render/envType
        - uses: copy
          config:
            inPath: ./meta/apps/codeai/envTypes/components
            outPath: ./render/components
        - uses: kustomize-set-image
          config:
            path: ./render/deploy
            images:
              - image: code-dot-org
                newName: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
        - uses: kustomize-build
          config:
            path: ./render/deploy
            outPath: ./out/${{ vars.renderPath }}
        - uses: git-commit
          config:
            path: ./out
            message: |
              Review ${{ vars.deployment }} render for ${{ vars.sourceCommit }} / ${{ imageFrom(vars.imageRepo).Tag }}
        - uses: git-push
          as: push
          config:
            path: ./out
            generateTargetBranch: true
        - uses: git-open-pr
          as: open-pr
          config:
            repoURL: ${{ vars.gitopsRepo }}
            sourceBranch: ${{ outputs.push.branch }}
            targetBranch: ${{ vars.targetBranch }}
            title: Review ${{ vars.deployment }} render
        - uses: git-wait-for-pr
          config:
            repoURL: ${{ vars.gitopsRepo }}
            prNumber: ${{ outputs['open-pr'].pr.id }}
