codeai_cluster_config:
  cluster_name:
  iam_arn_prefix:
  single_namespace_environment_types: []
  cluster_region: us-east-1
  frontend_security_group_namespaces: []
  cluster_primary_security_group_id: ""
  frontend_security_group_id: ""

adhoc:
  enabled: true
  environment_type: adhoc
  multi_namespace_regexes:
    - "^adhoc-.*"
