provider: aws

codeai_cluster_config:
  cluster_name:
  iam_arn_prefix:
  single_namespace_environment_types: []
  cluster_region: us-east-1

adhoc:
  enabled: true
  environment_type: adhoc
  multi_namespace_regexes:
    - "^adhoc-.*"
