image: ghcr.io/code-dot-org/cdo-rails@sha256:ecde664a0d80290992a8b0ad0eea86f807d8b2a1a8c9d6c546e985561e20887b
dnsName: studio.staging
user:
  uid: 0
  gid: 0
autoscaling:
  maxReplicas: 1
locals.yml:
  stack_name: staging
  override_dashboard: studio.staging.k8s.code.org
# argocd-detect-probe: k8s-gitops run 10 at 2026-03-22T10:10:09Z
