image: ghcr.io/code-dot-org/cdo-rails@sha256:811838fe444fcaa54728af2097fd66ebb1b63a88b5af691e3b289b3cb25d3d99
dnsName: studio.staging
user:
  uid: 0
  gid: 0
autoscaling:
  maxReplicas: 1
locals.yml:
  stack_name: staging
  override_dashboard: studio.staging.k8s.code.org
# argocd-detect-probe: k8s-gitops run 10 at 2026-03-22T10:10:09Z
