image: ghcr.io/code-dot-org/cdo-rails@sha256:02aa09f0b61363b8705b18c4314ca65478aed756ca01ceb1a1efc6f1ae1a9646
dnsName: studio.staging
user:
  uid: 0
  gid: 0
autoscaling:
  maxReplicas: 1
locals.yml:
  stack_name: staging
  override_dashboard: studio.staging.k8s.code.org
# argocd-detect-probe: k8s-gitops run 10 at 2026-03-22T10:10:09Z
