{{- $config := required "codeai_cluster_config is required" (index .Values "codeai_cluster_config") -}}
{{- $iamArnPrefix := required "codeai_cluster_config.iam_arn_prefix is required" (index $config "iam_arn_prefix") -}}
{{- $clusterName := required "codeai_cluster_config.cluster_name is required" (index $config "cluster_name") -}}
{{- range $index, $env := .Values.codeai_cluster_config.single_namespace_environment_types }}
{{- if gt $index 0 }}
---
{{- end }}
{{ include "eso-per-envtype.render" (dict
  "environment_type" $env
  "single_namespace_environment_type" true
  "multi_namespace_regexes" nil
  "iam_role_arn" (printf "%s:role/%s-eso-%s" $iamArnPrefix $clusterName $env)
  "region" $.Values.codeai_cluster_config.cluster_region
) | trim }}
{{- end }}
