{{- $config := required "codeai_cluster_config is required" (index .Values "codeai_cluster_config") -}}
{{- $clusterRegion := .Values.systemResources.secretStore.awsRegion | default (required "codeai_cluster_config.cluster_region is required" (index $config "cluster_region")) -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.systemResources.secretStore.name }}
  namespace: {{ .Values.systemResources.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ $clusterRegion | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.systemResources.secretStore.serviceAccountName }}
