apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.systemResources.secretStore.serviceAccountName }}
  namespace: {{ .Values.systemResources.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.systemResources.secretStore.iamRoleArn | quote }}
