apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  ignoreDifferences:
    - kind: MutatingWebhookConfiguration
      group: admissionregistration.k8s.io
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - kind: ValidatingWebhookConfiguration
      group: admissionregistration.k8s.io
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
  sources:
    - repoURL: https://github.com/code-dot-org/k8s-gitops.git
      targetRevision: main
      path: apps/infra/crossplane/chart
      helm:
        releaseName: crossplane
        valueFiles:
          - $values/apps/infra/codeai-cluster-config.values.yaml
    - repoURL: https://github.com/code-dot-org/k8s-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
