apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/code-dot-org/k8s-gitops.git
        revision: main
        files:
          - path: apps/*/application.yaml
          - path: apps/*/applicationset.yaml
  template:
    metadata:
      name: '{{.metadata.name}}'
    spec:
      project: '{{default "default" .spec.project}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      source: {}
  templatePatch: |
    {{- if or .spec.source .spec.sources }}
    metadata: {{ .metadata | toJson }}
    spec: {{ omit .spec "project" | toJson }}
    {{- else }}
    spec:
      source:
        repoURL: https://github.com/code-dot-org/k8s-gitops.git
        targetRevision: main
        path: {{ printf "apps/%s" .path.basename | toJson }}
        directory:
          include: "applicationset.yaml"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
        # We retry syncing our top-level apps in case one app creates CRDs
        # that another app depends on.
        retry:
          limit: 2
    {{- end }}
