apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - github.com/code-dot-org/code-dot-org//k8s/kustomize/base?ref=f33f9d20923c25a03e9e6da746f076c3ee4bb79d
components:
  - ../../envTypes/staging
images:
  - name: code-dot-org
    newName: ghcr.io/code-dot-org/code-dot-org
    newTag: git-f33f9d20923c25a03e9e6da746f076c3ee4bb79d
