apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: levelbuilder
resources:
  - github.com/code-dot-org/code-dot-org//k8s/kustomize/base?ref=8e63b725457dee9f56342b5c6bdd0c04789c08b7&timeout=120s
components:
  - ../../../envTypes/levelbuilder
images:
  - name: code-dot-org
    newName: ghcr.io/code-dot-org/code-dot-org
    newTag: git-8e63b725457dee9f56342b5c6bdd0c04789c08b7
